version: 2
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-and-monitor:
        branches:
            only:
              - master
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx tsc
    build-test:
        branches:
            ignore:
                - master
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
            - run: npx tsc

    