version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-monitor:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx tsc
    build-test:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
            - run: npx tsc
workflows:
    version: 2.1
    build-test-monitor:
        jobs:
            - build-test-monitor:
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                filters:
                    branches:
                        ignore:
                            - master